### ISSUE TITLE
The node is red warming

### ISSUE THREAD

**Issue by LittleTerry** [brunocbreis/pysion#9]
Thanks for your code! 
I run your code here https://github.com/brunocbreis/pysion/blob/main/examples/simple_title/simple_title.py
but I encounter this problem, the node is red warming and I have no images on screen.
<img width="849" alt="ces" src="https://user-images.githubusercontent.com/19617725/236634531-61b0e6d9-1e0e-4cc3-9b9b-d7f56c8f5399.png">

**Comment by brunocbreis** [comment]
Hi!! Glad you like the code. I know what's up: I used a font nobody has hahaha

If you change the font in the text node it should work properly.

**Comment by brunocbreis** [comment]
@LittleTerry if you try it again with the updated example, it should work out of the box.

**Comment by LittleTerry** [comment]
> @LittleTerry if you try it again with the updated example, it should work out of the box.

Hi, thanks for your repley and it works!
I have another question. I noticed another repo called pydavinci https://github.com/pedrolabonia/pydavinci, it can "control" davinci.

So I was wondering, can pysion combined with pydavinci? So that we do have to copy the nodes to davinci. 
In other words, can we create Fusion compositions directly and automatically?

For example, we need to link "MergeTitle" node and "MediaOut1" node manually. Can we do it automatically using your code?

Anyway, thanks for your work. Have a nice day!

<img width="832" alt="image" src="https://user-images.githubusercontent.com/19617725/236652883-2a6bed05-216b-4757-b6b6-5c5df88dbd78.png">

**Comment by brunocbreis** [comment]
Hey @LittleTerry! Check out the lines I added to the new file I just pushed to that same directory. That's all you need to add a MediaOut node. Try and paste that into Resolve to see if it helps.

**Comment by LittleTerry** [comment]
> Hey @LittleTerry! Check out the lines I added to the new file I just pushed to that same directory. That's all you need to add a MediaOut node. Try and paste that into Resolve to see if it helps.

Hi, I just gave it a try. It works! Now, "MergeTitle" node and "MediaOut1"  are linked automaticly. Cool!! Thanks for your work!

One more thing, can it be copied or transmited to Davinci automaticly? For example, using pydavinci? 
It would be so amazing if all the workflow can be automaticly. Sorry for my "laziness"...

**Comment by brunocbreis** [comment]
I would have to study this other codebase as its structure, I assume, is very different from pysion's. My code doesn't rely on DaVinci Resolve's API whatsoever, it's purely text based. I would assume it's possible to have them work together but I can't say how.

**Comment by LittleTerry** [comment]
> I would have to study this other codebase as its structure, I assume, is very different from pysion's. My code doesn't rely on DaVinci Resolve's API whatsoever, it's purely text based. I would assume it's possible to have them work together but I can't say how.

Thanks for your reply! Below is an simple example to use pydavinci to connect with Davinci. Hope it can help to inspire you

`from pydavinci import davinci

resolve = davinci.Resolve()

project = resolve.project
project_manager = resolve.project_manager
media_pool = resolve.media_pool
media_storage = resolve.media_storage

print(project)
`
